language: python

python:
  - "3.5"
  
services:
  - docker

branches:
    only:
        - master
  
notifications:
  email: false

before_install:
- docker pull zimmerman/phaseflow-fenics:latest

group: deprecated-2017Q2

script:
- docker run --rm -P -v `pwd`:/home/fenics/shared -w /home/fenics/shared zimmerman/phaseflow-fenics:latest "pip3 install --user --upgrade -r requirements.txt && python3 -m pytest -v -k '(not nightly)'" 
