language: python

python:
  - "3.5"
  
services:
  - docker

branches:
    only:
        - master
  
notifications:
  email: false

before_install:
- docker pull zimmerman/phaseflow-fenics:fenics-2017.1.0

script:
- docker run --rm -P -v `pwd`:/home/fenics/shared -w /home/fenics/shared zimmerman/phaseflow-fenics:fenics-2017.1.0 "pip3 install --user -r requirements.txt && pip3 install --user --upgrade . && python3 -m pytest -v -k '_ci_'" 
